### Says hello.
GET http://localhost:8080/hello
X-Hello-Header: 1
Content-Type: application/json

{
  "name": "Alex"
}


### Says goodbye.
GET http://localhost:8080/goodbye
Content-Type: application/json

{
  "name": "Mia"
}


