name: 'CI'
run-name: 'Build #${{ github.run_number }} - ${{ github.event.head_commit.message }}'

on:
  push:
    branches:
    - "bugfix/*"
    - "hotfix/*"
    - "feature/**"
    - "main"

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read


jobs:  
  RunTests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24.2' 

    - name: Run Terratest
      run: go test ./test/...