name: 'CI'
run-name: 'Build #${{ github.run_number }} - ${{ github.event.head_commit.message }}'

on:
  push:
    branches:
    - "main"

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:  
  RunTests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GH_TOKEN: ${{ secrets.PARMESAN_TOKEN }}